# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/giulia/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),giulia)

$(call add-radio-file-sha1-checked,radio/abl.img,15b708a19089332eab94332bb259b248b627663f)
$(call add-radio-file-sha1-checked,radio/aop.img,b9c9087c87741eb396dc9bcc481c1b5f33a21fd9)
$(call add-radio-file-sha1-checked,radio/aop_config.img,4414174358d3030aa040638ff204e8bc9beaf113)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,dcd779da5ecb8ce1bd2efa0f1d0560dfc3d63e37)
$(call add-radio-file-sha1-checked,radio/cpucp.img,638f2b9e37f22acbe08448eac2f1f70ba259d960)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,8f2ab21cc275b052d40fa84f37431f8cd02c4c5f)
$(call add-radio-file-sha1-checked,radio/devcfg.img,31323daf5aa79755052c1f73f2353f8366927934)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,728f22e2c64888c794f3aa92fcd79f424afcc095)
$(call add-radio-file-sha1-checked,radio/hyp.img,bceacde03e4c37adc752c3d4b16677b8904c998f)
$(call add-radio-file-sha1-checked,radio/imagefv.img,04264d5e757c212892cf4e913757fa81d5e84705)
$(call add-radio-file-sha1-checked,radio/keymaster.img,7d705db169fa5ec3eb26211c6dea8a67ae36c93b)
$(call add-radio-file-sha1-checked,radio/modem.img,a09ebda44506461ab3fd6f4393da610be05dbeb7)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,8bf1c8e3c88dda4e189b5a7c46c5d502ce04b3a1)
$(call add-radio-file-sha1-checked,radio/qupfw.img,c322c5c8bae3c627b4df6e2ad1ec830ad5d7436b)
$(call add-radio-file-sha1-checked,radio/shrm.img,b82cc667a1852789ba90f8381e643e6677c9a164)
$(call add-radio-file-sha1-checked,radio/splash.img,07e9cda27d7d55806370294443d78ef887e32d2b)
$(call add-radio-file-sha1-checked,radio/tz.img,8ba2d1fead265a699aa833046105464fcb3ffa97)
$(call add-radio-file-sha1-checked,radio/uefi.img,5f70200a8a604be4c96285d99181edca5d6c60dd)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9155b2e15d840100d2f93205bd4b6535a0d00087)
$(call add-radio-file-sha1-checked,radio/xbl.img,6543fb8647ccefecfb71dd3b7d1807c75035f10d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,d353a0af5578889fc64dc332e71e763f6590bae6)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,ee264d82f69bad6c940d1e71fc78534b4119bf20)

endif
